---
- name: Include nftables service
  include_tasks: nftables.yml

- name: Include install_packages
  include_tasks: install_packages.yml

- name: Include iscsi_initiator Configuring
  include_tasks: iscsi_initiator.yml

- name: Include multipath configure
  include_tasks: multipath.yml

- name: Include setup pcs service
  include_tasks: pcs_install.yml

- name: Include configure pcs service
  include_tasks: pcs_config1.yml
  when: "ansible_hostname in 'pcs-01'"

- name: Include lvm2
  include_tasks: lvm2.yml

- name: Include gfs2
  include_tasks: gfs2.yml
  when: "ansible_hostname in 'pcs-01'"

- name: Include configure pcs service
  include_tasks: pcs_config2.yml
  when: "ansible_hostname in 'pcs-01'"
